name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    env:
      TAG: "${{github.repository}}:${{github.sha}}"

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${TAG}"
    - name: Test Docker image, basic
      run: |
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" fcm make -C '/opt/test'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" '/opt/test/build/bin/hello.bin'
    - name: Test Docker image, build with netCDF
      run: |
        curl -L \
          'https://www.unidata.ucar.edu/software/netcdf/examples/programs/simple_xy_wr.f90' \
          -o 'test/src/simple_xy_wr.f90'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" \
          fcm make -C '/opt/test' -f '/opt/test/fcm-make-with-netcdf.cfg'
        docker run --rm -v "${PWD}/test:/opt/test" "${TAG}" \
          '/opt/test/build/bin/simple_xy_wr.bin'
        docker run --rm \
          -v "${PWD}/test:/var/task" \
          'lambci/lambda:python3.7' \
          'index.handler' \
          '{"executable": "/var/task/build/bin/simple_xy_wr.bin"}'
